//! Built-in terminal themes.

use tg_core::traits::theme::{
    Color, ColorPalette, EditorColors, GridColors, SemanticColors, SyntaxColors, Theme, ThemeMetadata,
};

fn metadata(name: &str, dark: bool) -> ThemeMetadata {
    ThemeMetadata {
        name: name.into(),
        author: Some("GetAGrip".into()),
        version: "1.0.0".into(),
        dark,
        description: Some(format!("Built-in {name} theme")),
        license: Some("MIT".into()),
        url: None,
    }
}

// ─── Catppuccin Mocha ──────────────────────────────────────────────

pub fn catppuccin_mocha() -> Theme {
    let palette = ColorPalette {
        background: Color::Hex("#1e1e2e".into()),
        foreground: Color::Hex("#cdd6f4".into()),
        black: Color::Hex("#45475a".into()),
        red: Color::Hex("#f38ba8".into()),
        green: Color::Hex("#a6e3a1".into()),
        yellow: Color::Hex("#f9e2af".into()),
        blue: Color::Hex("#89b4fa".into()),
        magenta: Color::Hex("#f5c2e7".into()),
        cyan: Color::Hex("#94e2d5".into()),
        white: Color::Hex("#bac2de".into()),
        bright_black: Color::Hex("#585b70".into()),
        bright_red: Color::Hex("#f38ba8".into()),
        bright_green: Color::Hex("#a6e3a1".into()),
        bright_yellow: Color::Hex("#f9e2af".into()),
        bright_blue: Color::Hex("#89b4fa".into()),
        bright_magenta: Color::Hex("#f5c2e7".into()),
        bright_cyan: Color::Hex("#94e2d5".into()),
        bright_white: Color::Hex("#a6adc8".into()),
        cursor: Color::Hex("#f5e0dc".into()),
        selection: Color::Hex("#585b70".into()),
    };
    Theme {
        metadata: metadata("catppuccin-mocha", true),
        palette,
        semantic: catppuccin_mocha_semantic(),
        syntax: catppuccin_mocha_syntax(),
        editor: catppuccin_mocha_editor(),
        grid: catppuccin_mocha_grid(),
    }
}

fn catppuccin_mocha_semantic() -> SemanticColors {
    SemanticColors {
        panel_bg: "#1e1e2e".into(),
        panel_border: "#45475a".into(),
        panel_border_active: "#89b4fa".into(),
        status_bar_bg: "#181825".into(),
        status_bar_fg: "#cdd6f4".into(),
        tab_bar_bg: "#11111b".into(),
        tab_active: "#1e1e2e".into(),
        tab_inactive: "#313244".into(),
        scrollbar_thumb: "#585b70".into(),
        scrollbar_track: "#1e1e2e".into(),
        command_palette_bg: "#313244".into(),
        command_palette_selected: "#45475a".into(),
        error: "#f38ba8".into(),
        warning: "#fab387".into(),
        info: "#89b4fa".into(),
        success: "#a6e3a1".into(),
        breadcrumb: "#6c7086".into(),
        line_number: "#585b70".into(),
        line_number_active: "#cdd6f4".into(),
        gutter_bg: "#1e1e2e".into(),
        search_highlight: "#f9e2af".into(),
        search_match: "#fab387".into(),
    }
}

fn catppuccin_mocha_syntax() -> SyntaxColors {
    SyntaxColors {
        keyword: "#cba6f7".into(),
        datatype: "#f9e2af".into(),
        string: "#a6e3a1".into(),
        number: "#fab387".into(),
        comment: "#6c7086".into(),
        identifier: "#cdd6f4".into(),
        function: "#89b4fa".into(),
        operator: "#89dceb".into(),
        punctuation: "#bac2de".into(),
        alias: "#89b4fa".into(),
        table: "#74c7ec".into(),
        column: "#cdd6f4".into(),
        parameter: "#f5c2e7".into(),
        cte: "#94e2d5".into(),
        boolean: "#fab387".into(),
        null: "#f38ba8".into(),
        error_underline: "#f38ba8".into(),
        warning_underline: "#f9e2af".into(),
        info_underline: "#89b4fa".into(),
        bracket_match: "#a6e3a1".into(),
        bracket_mismatch: "#f38ba8".into(),
    }
}

fn catppuccin_mocha_editor() -> EditorColors {
    EditorColors {
        bg: "#1e1e2e".into(),
        fg: "#cdd6f4".into(),
        cursor: "#f5e0dc".into(),
        selection_bg: "#585b70".into(),
        line_highlight: "#313244".into(),
        whitespace: "#45475a".into(),
        indent_guide: "#45475a".into(),
        fold_marker: "#6c7086".into(),
        minimap_bg: "#181825".into(),
        minimap_viewport: "#585b70".into(),
    }
}

fn catppuccin_mocha_grid() -> GridColors {
    GridColors {
        bg: "#1e1e2e".into(),
        header_bg: "#313244".into(),
        header_fg: "#cdd6f4".into(),
        border: "#45475a".into(),
        row_even_bg: "#1e1e2e".into(),
        row_odd_bg: "#181825".into(),
        row_selected_bg: "#45475a".into(),
        null_fg: "#585b70".into(),
        modified_fg: "#f9e2af".into(),
        cell_focus: "#89b4fa".into(),
        resize_handle: "#585b70".into(),
    }
}

// ─── Catppuccin Latte ──────────────────────────────────────────────

pub fn catppuccin_latte() -> Theme {
    let palette = ColorPalette {
        background: Color::Hex("#eff1f5".into()),
        foreground: Color::Hex("#4c4f69".into()),
        black: Color::Hex("#dce0e8".into()),
        red: Color::Hex("#d20f39".into()),
        green: Color::Hex("#40a02b".into()),
        yellow: Color::Hex("#df8e1d".into()),
        blue: Color::Hex("#1e66f5".into()),
        magenta: Color::Hex("#8839ef".into()),
        cyan: Color::Hex("#179299".into()),
        white: Color::Hex("#9ca0b0".into()),
        bright_black: Color::Hex("#ccd0da".into()),
        bright_red: Color::Hex("#d20f39".into()),
        bright_green: Color::Hex("#40a02b".into()),
        bright_yellow: Color::Hex("#df8e1d".into()),
        bright_blue: Color::Hex("#1e66f5".into()),
        bright_magenta: Color::Hex("#8839ef".into()),
        bright_cyan: Color::Hex("#179299".into()),
        bright_white: Color::Hex("#acb0be".into()),
        cursor: Color::Hex("#dc8a78".into()),
        selection: Color::Hex("#ccd0da".into()),
    };

    let semantic = SemanticColors {
        panel_bg: "#eff1f5".into(),
        panel_border: "#ccd0da".into(),
        panel_border_active: "#1e66f5".into(),
        status_bar_bg: "#e6e9ef".into(),
        status_bar_fg: "#4c4f69".into(),
        tab_bar_bg: "#dce0e8".into(),
        tab_active: "#eff1f5".into(),
        tab_inactive: "#ccd0da".into(),
        scrollbar_thumb: "#acb0be".into(),
        scrollbar_track: "#eff1f5".into(),
        command_palette_bg: "#ccd0da".into(),
        command_palette_selected: "#acb0be".into(),
        error: "#d20f39".into(),
        warning: "#fe640b".into(),
        info: "#1e66f5".into(),
        success: "#40a02b".into(),
        breadcrumb: "#9ca0b0".into(),
        line_number: "#acb0be".into(),
        line_number_active: "#4c4f69".into(),
        gutter_bg: "#eff1f5".into(),
        search_highlight: "#df8e1d".into(),
        search_match: "#fe640b".into(),
    };

    let syntax = SyntaxColors {
        keyword: "#8839ef".into(),
        datatype: "#df8e1d".into(),
        string: "#40a02b".into(),
        number: "#fe640b".into(),
        comment: "#9ca0b0".into(),
        identifier: "#4c4f69".into(),
        function: "#1e66f5".into(),
        operator: "#179299".into(),
        punctuation: "#9ca0b0".into(),
        alias: "#1e66f5".into(),
        table: "#209fb5".into(),
        column: "#4c4f69".into(),
        parameter: "#8839ef".into(),
        cte: "#179299".into(),
        boolean: "#fe640b".into(),
        null: "#d20f39".into(),
        error_underline: "#d20f39".into(),
        warning_underline: "#df8e1d".into(),
        info_underline: "#1e66f5".into(),
        bracket_match: "#40a02b".into(),
        bracket_mismatch: "#d20f39".into(),
    };

    Theme {
        metadata: metadata("catppuccin-latte", false),
        palette,
        semantic,
        syntax,
        editor: EditorColors {
            bg: "#eff1f5".into(),
            fg: "#4c4f69".into(),
            cursor: "#dc8a78".into(),
            selection_bg: "#acb0be".into(),
            line_highlight: "#ccd0da".into(),
            whitespace: "#ccd0da".into(),
            indent_guide: "#ccd0da".into(),
            fold_marker: "#9ca0b0".into(),
            minimap_bg: "#e6e9ef".into(),
            minimap_viewport: "#acb0be".into(),
        },
        grid: GridColors {
            bg: "#eff1f5".into(),
            header_bg: "#ccd0da".into(),
            header_fg: "#4c4f69".into(),
            border: "#ccd0da".into(),
            row_even_bg: "#eff1f5".into(),
            row_odd_bg: "#e6e9ef".into(),
            row_selected_bg: "#ccd0da".into(),
            null_fg: "#9ca0b0".into(),
            modified_fg: "#df8e1d".into(),
            cell_focus: "#1e66f5".into(),
            resize_handle: "#acb0be".into(),
        },
    }
}

// ─── Tokyo Night ───────────────────────────────────────────────────

pub fn tokyo_night() -> Theme {
    let palette = ColorPalette {
        background: Color::Hex("#1a1b26".into()),
        foreground: Color::Hex("#a9b1d6".into()),
        black: Color::Hex("#32344a".into()),
        red: Color::Hex("#f7768e".into()),
        green: Color::Hex("#9ece6a".into()),
        yellow: Color::Hex("#e0af68".into()),
        blue: Color::Hex("#7aa2f7".into()),
        magenta: Color::Hex("#ad8ee6".into()),
        cyan: Color::Hex("#449dab".into()),
        white: Color::Hex("#787c99".into()),
        bright_black: Color::Hex("#444b6a".into()),
        bright_red: Color::Hex("#ff7a93".into()),
        bright_green: Color::Hex("#b9f27c".into()),
        bright_yellow: Color::Hex("#ff9e64".into()),
        bright_blue: Color::Hex("#7da6ff".into()),
        bright_magenta: Color::Hex("#bb9af7".into()),
        bright_cyan: Color::Hex("#0db9d7".into()),
        bright_white: Color::Hex("#acb0d0".into()),
        cursor: Color::Hex("#c0caf5".into()),
        selection: Color::Hex("#33467c".into()),
    };
    Theme {
        metadata: metadata("tokyo-night", true),
        palette,
        semantic: SemanticColors {
            panel_bg: "#1a1b26".into(),
            panel_border: "#32344a".into(),
            panel_border_active: "#7aa2f7".into(),
            status_bar_bg: "#16161e".into(),
            status_bar_fg: "#a9b1d6".into(),
            tab_bar_bg: "#16161e".into(),
            tab_active: "#1a1b26".into(),
            tab_inactive: "#292e42".into(),
            scrollbar_thumb: "#444b6a".into(),
            scrollbar_track: "#1a1b26".into(),
            command_palette_bg: "#292e42".into(),
            command_palette_selected: "#32344a".into(),
            error: "#f7768e".into(),
            warning: "#e0af68".into(),
            info: "#7aa2f7".into(),
            success: "#9ece6a".into(),
            breadcrumb: "#565f89".into(),
            line_number: "#3b4261".into(),
            line_number_active: "#a9b1d6".into(),
            gutter_bg: "#1a1b26".into(),
            search_highlight: "#e0af68".into(),
            search_match: "#ff9e64".into(),
        },
        syntax: SyntaxColors {
            keyword: "#ad8ee6".into(),
            datatype: "#e0af68".into(),
            string: "#9ece6a".into(),
            number: "#ff9e64".into(),
            comment: "#565f89".into(),
            identifier: "#a9b1d6".into(),
            function: "#7aa2f7".into(),
            operator: "#449dab".into(),
            punctuation: "#787c99".into(),
            alias: "#7aa2f7".into(),
            table: "#0db9d7".into(),
            column: "#a9b1d6".into(),
            parameter: "#bb9af7".into(),
            cte: "#449dab".into(),
            boolean: "#ff9e64".into(),
            null: "#f7768e".into(),
            error_underline: "#f7768e".into(),
            warning_underline: "#e0af68".into(),
            info_underline: "#7aa2f7".into(),
            bracket_match: "#9ece6a".into(),
            bracket_mismatch: "#f7768e".into(),
        },
        editor: EditorColors {
            bg: "#1a1b26".into(),
            fg: "#a9b1d6".into(),
            cursor: "#c0caf5".into(),
            selection_bg: "#33467c".into(),
            line_highlight: "#292e42".into(),
            whitespace: "#32344a".into(),
            indent_guide: "#32344a".into(),
            fold_marker: "#565f89".into(),
            minimap_bg: "#16161e".into(),
            minimap_viewport: "#444b6a".into(),
        },
        grid: GridColors {
            bg: "#1a1b26".into(),
            header_bg: "#292e42".into(),
            header_fg: "#a9b1d6".into(),
            border: "#32344a".into(),
            row_even_bg: "#1a1b26".into(),
            row_odd_bg: "#16161e".into(),
            row_selected_bg: "#33467c".into(),
            null_fg: "#565f89".into(),
            modified_fg: "#e0af68".into(),
            cell_focus: "#7aa2f7".into(),
            resize_handle: "#444b6a".into(),
        },
    }
}

// ─── Tokyo Night Storm ─────────────────────────────────────────────

pub fn tokyo_night_storm() -> Theme {
    let mut theme = tokyo_night();
    theme.metadata.name = "tokyo-night-storm".into();
    theme.metadata.description = Some("Built-in Tokyo Night Storm theme".into());
    theme.palette.background = Color::Hex("#24283b".into());
    theme.editor.bg = "#24283b".into();
    theme.grid.bg = "#24283b".into();
    theme.grid.row_even_bg = "#24283b".into();
    theme.grid.row_odd_bg = "#1f2335".into();
    theme.semantic.panel_bg = "#24283b".into();
    theme.semantic.status_bar_bg = "#1f2335".into();
    theme.semantic.tab_bar_bg = "#1f2335".into();
    theme.semantic.tab_active = "#24283b".into();
    theme
}

// ─── Nord ──────────────────────────────────────────────────────────

pub fn nord() -> Theme {
    let palette = ColorPalette {
        background: Color::Hex("#2e3440".into()),
        foreground: Color::Hex("#d8dee9".into()),
        black: Color::Hex("#3b4252".into()),
        red: Color::Hex("#bf616a".into()),
        green: Color::Hex("#a3be8c".into()),
        yellow: Color::Hex("#ebcb8b".into()),
        blue: Color::Hex("#81a1c1".into()),
        magenta: Color::Hex("#b48ead".into()),
        cyan: Color::Hex("#88c0d0".into()),
        white: Color::Hex("#e5e9f0".into()),
        bright_black: Color::Hex("#4c566a".into()),
        bright_red: Color::Hex("#bf616a".into()),
        bright_green: Color::Hex("#a3be8c".into()),
        bright_yellow: Color::Hex("#ebcb8b".into()),
        bright_blue: Color::Hex("#81a1c1".into()),
        bright_magenta: Color::Hex("#b48ead".into()),
        bright_cyan: Color::Hex("#8fbcbb".into()),
        bright_white: Color::Hex("#eceff4".into()),
        cursor: Color::Hex("#d8dee9".into()),
        selection: Color::Hex("#434c5e".into()),
    };
    Theme {
        metadata: metadata("nord", true),
        palette,
        semantic: SemanticColors {
            panel_bg: "#2e3440".into(),
            panel_border: "#4c566a".into(),
            panel_border_active: "#88c0d0".into(),
            status_bar_bg: "#3b4252".into(),
            status_bar_fg: "#d8dee9".into(),
            tab_bar_bg: "#2e3440".into(),
            tab_active: "#3b4252".into(),
            tab_inactive: "#2e3440".into(),
            scrollbar_thumb: "#4c566a".into(),
            scrollbar_track: "#2e3440".into(),
            command_palette_bg: "#3b4252".into(),
            command_palette_selected: "#434c5e".into(),
            error: "#bf616a".into(),
            warning: "#d08770".into(),
            info: "#81a1c1".into(),
            success: "#a3be8c".into(),
            breadcrumb: "#4c566a".into(),
            line_number: "#4c566a".into(),
            line_number_active: "#d8dee9".into(),
            gutter_bg: "#2e3440".into(),
            search_highlight: "#ebcb8b".into(),
            search_match: "#d08770".into(),
        },
        syntax: SyntaxColors {
            keyword: "#81a1c1".into(),
            datatype: "#8fbcbb".into(),
            string: "#a3be8c".into(),
            number: "#b48ead".into(),
            comment: "#616e88".into(),
            identifier: "#d8dee9".into(),
            function: "#88c0d0".into(),
            operator: "#81a1c1".into(),
            punctuation: "#d8dee9".into(),
            alias: "#88c0d0".into(),
            table: "#8fbcbb".into(),
            column: "#d8dee9".into(),
            parameter: "#b48ead".into(),
            cte: "#8fbcbb".into(),
            boolean: "#b48ead".into(),
            null: "#bf616a".into(),
            error_underline: "#bf616a".into(),
            warning_underline: "#ebcb8b".into(),
            info_underline: "#81a1c1".into(),
            bracket_match: "#a3be8c".into(),
            bracket_mismatch: "#bf616a".into(),
        },
        editor: EditorColors {
            bg: "#2e3440".into(),
            fg: "#d8dee9".into(),
            cursor: "#d8dee9".into(),
            selection_bg: "#434c5e".into(),
            line_highlight: "#3b4252".into(),
            whitespace: "#4c566a".into(),
            indent_guide: "#4c566a".into(),
            fold_marker: "#616e88".into(),
            minimap_bg: "#242933".into(),
            minimap_viewport: "#4c566a".into(),
        },
        grid: GridColors {
            bg: "#2e3440".into(),
            header_bg: "#3b4252".into(),
            header_fg: "#d8dee9".into(),
            border: "#4c566a".into(),
            row_even_bg: "#2e3440".into(),
            row_odd_bg: "#3b4252".into(),
            row_selected_bg: "#434c5e".into(),
            null_fg: "#4c566a".into(),
            modified_fg: "#ebcb8b".into(),
            cell_focus: "#88c0d0".into(),
            resize_handle: "#4c566a".into(),
        },
    }
}

// ─── Gruvbox Dark ──────────────────────────────────────────────────

pub fn gruvbox_dark() -> Theme {
    let palette = ColorPalette {
        background: Color::Hex("#282828".into()),
        foreground: Color::Hex("#ebdbb2".into()),
        black: Color::Hex("#282828".into()),
        red: Color::Hex("#cc241d".into()),
        green: Color::Hex("#98971a".into()),
        yellow: Color::Hex("#d79921".into()),
        blue: Color::Hex("#458588".into()),
        magenta: Color::Hex("#b16286".into()),
        cyan: Color::Hex("#689d6a".into()),
        white: Color::Hex("#a89984".into()),
        bright_black: Color::Hex("#928374".into()),
        bright_red: Color::Hex("#fb4934".into()),
        bright_green: Color::Hex("#b8bb26".into()),
        bright_yellow: Color::Hex("#fabd2f".into()),
        bright_blue: Color::Hex("#83a598".into()),
        bright_magenta: Color::Hex("#d3869b".into()),
        bright_cyan: Color::Hex("#8ec07c".into()),
        bright_white: Color::Hex("#ebdbb2".into()),
        cursor: Color::Hex("#ebdbb2".into()),
        selection: Color::Hex("#665c54".into()),
    };
    Theme {
        metadata: metadata("gruvbox-dark", true),
        palette,
        semantic: SemanticColors {
            panel_bg: "#282828".into(),
            panel_border: "#665c54".into(),
            panel_border_active: "#d79921".into(),
            status_bar_bg: "#1d2021".into(),
            status_bar_fg: "#ebdbb2".into(),
            tab_bar_bg: "#1d2021".into(),
            tab_active: "#282828".into(),
            tab_inactive: "#3c3836".into(),
            scrollbar_thumb: "#665c54".into(),
            scrollbar_track: "#282828".into(),
            command_palette_bg: "#3c3836".into(),
            command_palette_selected: "#504945".into(),
            error: "#cc241d".into(),
            warning: "#d65d0e".into(),
            info: "#458588".into(),
            success: "#98971a".into(),
            breadcrumb: "#928374".into(),
            line_number: "#665c54".into(),
            line_number_active: "#a89984".into(),
            gutter_bg: "#282828".into(),
            search_highlight: "#d79921".into(),
            search_match: "#fabd2f".into(),
        },
        syntax: SyntaxColors {
            keyword: "#fb4934".into(),
            datatype: "#fabd2f".into(),
            string: "#b8bb26".into(),
            number: "#d3869b".into(),
            comment: "#928374".into(),
            identifier: "#ebdbb2".into(),
            function: "#83a598".into(),
            operator: "#fe8019".into(),
            punctuation: "#a89984".into(),
            alias: "#8ec07c".into(),
            table: "#83a598".into(),
            column: "#ebdbb2".into(),
            parameter: "#d3869b".into(),
            cte: "#8ec07c".into(),
            boolean: "#d3869b".into(),
            null: "#fb4934".into(),
            error_underline: "#fb4934".into(),
            warning_underline: "#fabd2f".into(),
            info_underline: "#83a598".into(),
            bracket_match: "#b8bb26".into(),
            bracket_mismatch: "#fb4934".into(),
        },
        editor: EditorColors {
            bg: "#282828".into(),
            fg: "#ebdbb2".into(),
            cursor: "#ebdbb2".into(),
            selection_bg: "#504945".into(),
            line_highlight: "#3c3836".into(),
            whitespace: "#504945".into(),
            indent_guide: "#504945".into(),
            fold_marker: "#928374".into(),
            minimap_bg: "#1d2021".into(),
            minimap_viewport: "#665c54".into(),
        },
        grid: GridColors {
            bg: "#282828".into(),
            header_bg: "#3c3836".into(),
            header_fg: "#ebdbb2".into(),
            border: "#504945".into(),
            row_even_bg: "#282828".into(),
            row_odd_bg: "#1d2021".into(),
            row_selected_bg: "#504945".into(),
            null_fg: "#665c54".into(),
            modified_fg: "#d79921".into(),
            cell_focus: "#fe8019".into(),
            resize_handle: "#665c54".into(),
        },
    }
}

// ─── Gruvbox Light ─────────────────────────────────────────────────

pub fn gruvbox_light() -> Theme {
    let palette = ColorPalette {
        background: Color::Hex("#fbf1c7".into()),
        foreground: Color::Hex("#3c3836".into()),
        black: Color::Hex("#fbf1c7".into()),
        red: Color::Hex("#cc241d".into()),
        green: Color::Hex("#98971a".into()),
        yellow: Color::Hex("#d79921".into()),
        blue: Color::Hex("#458588".into()),
        magenta: Color::Hex("#b16286".into()),
        cyan: Color::Hex("#689d6a".into()),
        white: Color::Hex("#7c6f64".into()),
        bright_black: Color::Hex("#928374".into()),
        bright_red: Color::Hex("#9d0006".into()),
        bright_green: Color::Hex("#79740e".into()),
        bright_yellow: Color::Hex("#b57614".into()),
        bright_blue: Color::Hex("#076678".into()),
        bright_magenta: Color::Hex("#8f3f71".into()),
        bright_cyan: Color::Hex("#427b58".into()),
        bright_white: Color::Hex("#3c3836".into()),
        cursor: Color::Hex("#282828".into()),
        selection: Color::Hex("#d5c4a1".into()),
    };
    Theme {
        metadata: metadata("gruvbox-light", false),
        palette,
        semantic: SemanticColors {
            panel_bg: "#fbf1c7".into(),
            panel_border: "#d5c4a1".into(),
            panel_border_active: "#d79921".into(),
            status_bar_bg: "#ebdbb2".into(),
            status_bar_fg: "#3c3836".into(),
            tab_bar_bg: "#ebdbb2".into(),
            tab_active: "#fbf1c7".into(),
            tab_inactive: "#d5c4a1".into(),
            scrollbar_thumb: "#bdae93".into(),
            scrollbar_track: "#fbf1c7".into(),
            command_palette_bg: "#ebdbb2".into(),
            command_palette_selected: "#d5c4a1".into(),
            error: "#9d0006".into(),
            warning: "#b57614".into(),
            info: "#076678".into(),
            success: "#79740e".into(),
            breadcrumb: "#a89984".into(),
            line_number: "#bdae93".into(),
            line_number_active: "#3c3836".into(),
            gutter_bg: "#fbf1c7".into(),
            search_highlight: "#d79921".into(),
            search_match: "#b57614".into(),
        },
        syntax: SyntaxColors {
            keyword: "#9d0006".into(),
            datatype: "#b57614".into(),
            string: "#79740e".into(),
            number: "#8f3f71".into(),
            comment: "#a89984".into(),
            identifier: "#3c3836".into(),
            function: "#076678".into(),
            operator: "#af3a03".into(),
            punctuation: "#7c6f64".into(),
            alias: "#427b58".into(),
            table: "#076678".into(),
            column: "#3c3836".into(),
            parameter: "#8f3f71".into(),
            cte: "#427b58".into(),
            boolean: "#8f3f71".into(),
            null: "#9d0006".into(),
            error_underline: "#9d0006".into(),
            warning_underline: "#b57614".into(),
            info_underline: "#076678".into(),
            bracket_match: "#79740e".into(),
            bracket_mismatch: "#9d0006".into(),
        },
        editor: EditorColors {
            bg: "#fbf1c7".into(),
            fg: "#3c3836".into(),
            cursor: "#282828".into(),
            selection_bg: "#d5c4a1".into(),
            line_highlight: "#ebdbb2".into(),
            whitespace: "#d5c4a1".into(),
            indent_guide: "#d5c4a1".into(),
            fold_marker: "#a89984".into(),
            minimap_bg: "#f2e5bc".into(),
            minimap_viewport: "#bdae93".into(),
        },
        grid: GridColors {
            bg: "#fbf1c7".into(),
            header_bg: "#ebdbb2".into(),
            header_fg: "#3c3836".into(),
            border: "#d5c4a1".into(),
            row_even_bg: "#fbf1c7".into(),
            row_odd_bg: "#f2e5bc".into(),
            row_selected_bg: "#d5c4a1".into(),
            null_fg: "#bdae93".into(),
            modified_fg: "#b57614".into(),
            cell_focus: "#076678".into(),
            resize_handle: "#bdae93".into(),
        },
    }
}

// ─── Dracula ───────────────────────────────────────────────────────

pub fn dracula() -> Theme {
    let palette = ColorPalette {
        background: Color::Hex("#282a36".into()),
        foreground: Color::Hex("#f8f8f2".into()),
        black: Color::Hex("#21222c".into()),
        red: Color::Hex("#ff5555".into()),
        green: Color::Hex("#50fa7b".into()),
        yellow: Color::Hex("#f1fa8c".into()),
        blue: Color::Hex("#bd93f9".into()),
        magenta: Color::Hex("#ff79c6".into()),
        cyan: Color::Hex("#8be9fd".into()),
        white: Color::Hex("#f8f8f2".into()),
        bright_black: Color::Hex("#6272a4".into()),
        bright_red: Color::Hex("#ff6e6e".into()),
        bright_green: Color::Hex("#69ff94".into()),
        bright_yellow: Color::Hex("#ffffa5".into()),
        bright_blue: Color::Hex("#d6acff".into()),
        bright_magenta: Color::Hex("#ff92df".into()),
        bright_cyan: Color::Hex("#a4ffff".into()),
        bright_white: Color::Hex("#ffffff".into()),
        cursor: Color::Hex("#f8f8f2".into()),
        selection: Color::Hex("#44475a".into()),
    };
    Theme {
        metadata: metadata("dracula", true),
        palette,
        semantic: SemanticColors {
            panel_bg: "#282a36".into(),
            panel_border: "#44475a".into(),
            panel_border_active: "#bd93f9".into(),
            status_bar_bg: "#21222c".into(),
            status_bar_fg: "#f8f8f2".into(),
            tab_bar_bg: "#21222c".into(),
            tab_active: "#282a36".into(),
            tab_inactive: "#44475a".into(),
            scrollbar_thumb: "#6272a4".into(),
            scrollbar_track: "#282a36".into(),
            command_palette_bg: "#44475a".into(),
            command_palette_selected: "#6272a4".into(),
            error: "#ff5555".into(),
            warning: "#ffb86c".into(),
            info: "#8be9fd".into(),
            success: "#50fa7b".into(),
            breadcrumb: "#6272a4".into(),
            line_number: "#6272a4".into(),
            line_number_active: "#f8f8f2".into(),
            gutter_bg: "#282a36".into(),
            search_highlight: "#f1fa8c".into(),
            search_match: "#ffb86c".into(),
        },
        syntax: SyntaxColors {
            keyword: "#ff79c6".into(),
            datatype: "#8be9fd".into(),
            string: "#f1fa8c".into(),
            number: "#bd93f9".into(),
            comment: "#6272a4".into(),
            identifier: "#f8f8f2".into(),
            function: "#50fa7b".into(),
            operator: "#ff79c6".into(),
            punctuation: "#f8f8f2".into(),
            alias: "#50fa7b".into(),
            table: "#8be9fd".into(),
            column: "#f8f8f2".into(),
            parameter: "#ffb86c".into(),
            cte: "#8be9fd".into(),
            boolean: "#bd93f9".into(),
            null: "#ff5555".into(),
            error_underline: "#ff5555".into(),
            warning_underline: "#f1fa8c".into(),
            info_underline: "#8be9fd".into(),
            bracket_match: "#50fa7b".into(),
            bracket_mismatch: "#ff5555".into(),
        },
        editor: EditorColors {
            bg: "#282a36".into(),
            fg: "#f8f8f2".into(),
            cursor: "#f8f8f2".into(),
            selection_bg: "#44475a".into(),
            line_highlight: "#44475a".into(),
            whitespace: "#44475a".into(),
            indent_guide: "#44475a".into(),
            fold_marker: "#6272a4".into(),
            minimap_bg: "#21222c".into(),
            minimap_viewport: "#6272a4".into(),
        },
        grid: GridColors {
            bg: "#282a36".into(),
            header_bg: "#44475a".into(),
            header_fg: "#f8f8f2".into(),
            border: "#44475a".into(),
            row_even_bg: "#282a36".into(),
            row_odd_bg: "#21222c".into(),
            row_selected_bg: "#44475a".into(),
            null_fg: "#6272a4".into(),
            modified_fg: "#f1fa8c".into(),
            cell_focus: "#bd93f9".into(),
            resize_handle: "#6272a4".into(),
        },
    }
}

// ─── One Dark ──────────────────────────────────────────────────────

pub fn one_dark() -> Theme {
    let palette = ColorPalette {
        background: Color::Hex("#282c34".into()),
        foreground: Color::Hex("#abb2bf".into()),
        black: Color::Hex("#282c34".into()),
        red: Color::Hex("#e06c75".into()),
        green: Color::Hex("#98c379".into()),
        yellow: Color::Hex("#e5c07b".into()),
        blue: Color::Hex("#61afef".into()),
        magenta: Color::Hex("#c678dd".into()),
        cyan: Color::Hex("#56b6c2".into()),
        white: Color::Hex("#abb2bf".into()),
        bright_black: Color::Hex("#545862".into()),
        bright_red: Color::Hex("#e06c75".into()),
        bright_green: Color::Hex("#98c379".into()),
        bright_yellow: Color::Hex("#e5c07b".into()),
        bright_blue: Color::Hex("#61afef".into()),
        bright_magenta: Color::Hex("#c678dd".into()),
        bright_cyan: Color::Hex("#56b6c2".into()),
        bright_white: Color::Hex("#c8ccd4".into()),
        cursor: Color::Hex("#528bff".into()),
        selection: Color::Hex("#3e4451".into()),
    };
    Theme {
        metadata: metadata("one-dark", true),
        palette,
        semantic: SemanticColors {
            panel_bg: "#282c34".into(),
            panel_border: "#181a1f".into(),
            panel_border_active: "#61afef".into(),
            status_bar_bg: "#21252b".into(),
            status_bar_fg: "#abb2bf".into(),
            tab_bar_bg: "#21252b".into(),
            tab_active: "#282c34".into(),
            tab_inactive: "#2c313a".into(),
            scrollbar_thumb: "#545862".into(),
            scrollbar_track: "#282c34".into(),
            command_palette_bg: "#2c313a".into(),
            command_palette_selected: "#3e4451".into(),
            error: "#e06c75".into(),
            warning: "#d19a66".into(),
            info: "#61afef".into(),
            success: "#98c379".into(),
            breadcrumb: "#545862".into(),
            line_number: "#4b5263".into(),
            line_number_active: "#c8ccd4".into(),
            gutter_bg: "#282c34".into(),
            search_highlight: "#e5c07b".into(),
            search_match: "#d19a66".into(),
        },
        syntax: SyntaxColors {
            keyword: "#c678dd".into(),
            datatype: "#e5c07b".into(),
            string: "#98c379".into(),
            number: "#d19a66".into(),
            comment: "#5c6370".into(),
            identifier: "#abb2bf".into(),
            function: "#61afef".into(),
            operator: "#56b6c2".into(),
            punctuation: "#abb2bf".into(),
            alias: "#61afef".into(),
            table: "#56b6c2".into(),
            column: "#abb2bf".into(),
            parameter: "#e06c75".into(),
            cte: "#56b6c2".into(),
            boolean: "#d19a66".into(),
            null: "#e06c75".into(),
            error_underline: "#e06c75".into(),
            warning_underline: "#e5c07b".into(),
            info_underline: "#61afef".into(),
            bracket_match: "#98c379".into(),
            bracket_mismatch: "#e06c75".into(),
        },
        editor: EditorColors {
            bg: "#282c34".into(),
            fg: "#abb2bf".into(),
            cursor: "#528bff".into(),
            selection_bg: "#3e4451".into(),
            line_highlight: "#2c313a".into(),
            whitespace: "#3e4451".into(),
            indent_guide: "#3e4451".into(),
            fold_marker: "#5c6370".into(),
            minimap_bg: "#21252b".into(),
            minimap_viewport: "#545862".into(),
        },
        grid: GridColors {
            bg: "#282c34".into(),
            header_bg: "#21252b".into(),
            header_fg: "#abb2bf".into(),
            border: "#181a1f".into(),
            row_even_bg: "#282c34".into(),
            row_odd_bg: "#21252b".into(),
            row_selected_bg: "#3e4451".into(),
            null_fg: "#545862".into(),
            modified_fg: "#e5c07b".into(),
            cell_focus: "#61afef".into(),
            resize_handle: "#545862".into(),
        },
    }
}

// ─── Kanagawa ──────────────────────────────────────────────────────

pub fn kanagawa() -> Theme {
    let palette = ColorPalette {
        background: Color::Hex("#1f1f28".into()),
        foreground: Color::Hex("#dcd7ba".into()),
        black: Color::Hex("#090618".into()),
        red: Color::Hex("#c34043".into()),
        green: Color::Hex("#76946a".into()),
        yellow: Color::Hex("#c0a36e".into()),
        blue: Color::Hex("#7e9cd8".into()),
        magenta: Color::Hex("#957fb8".into()),
        cyan: Color::Hex("#6a9589".into()),
        white: Color::Hex("#c8c093".into()),
        bright_black: Color::Hex("#727169".into()),
        bright_red: Color::Hex("#e82424".into()),
        bright_green: Color::Hex("#98bb6c".into()),
        bright_yellow: Color::Hex("#e6c384".into()),
        bright_blue: Color::Hex("#7fb4ca".into()),
        bright_magenta: Color::Hex("#938aa9".into()),
        bright_cyan: Color::Hex("#7aa89f".into()),
        bright_white: Color::Hex("#dcd7ba".into()),
        cursor: Color::Hex("#c8c093".into()),
        selection: Color::Hex("#2d4f67".into()),
    };
    Theme {
        metadata: metadata("kanagawa", true),
        palette,
        semantic: SemanticColors {
            panel_bg: "#1f1f28".into(),
            panel_border: "#16161d".into(),
            panel_border_active: "#7e9cd8".into(),
            status_bar_bg: "#16161d".into(),
            status_bar_fg: "#dcd7ba".into(),
            tab_bar_bg: "#16161d".into(),
            tab_active: "#1f1f28".into(),
            tab_inactive: "#223249".into(),
            scrollbar_thumb: "#54546d".into(),
            scrollbar_track: "#1f1f28".into(),
            command_palette_bg: "#223249".into(),
            command_palette_selected: "#2a3b54".into(),
            error: "#c34043".into(),
            warning: "#ffa066".into(),
            info: "#7e9cd8".into(),
            success: "#76946a".into(),
            breadcrumb: "#54546d".into(),
            line_number: "#54546d".into(),
            line_number_active: "#c8c093".into(),
            gutter_bg: "#1f1f28".into(),
            search_highlight: "#c0a36e".into(),
            search_match: "#ffa066".into(),
        },
        syntax: SyntaxColors {
            keyword: "#957fb8".into(),
            datatype: "#c0a36e".into(),
            string: "#76946a".into(),
            number: "#d27e99".into(),
            comment: "#727169".into(),
            identifier: "#dcd7ba".into(),
            function: "#7e9cd8".into(),
            operator: "#6a9589".into(),
            punctuation: "#c8c093".into(),
            alias: "#7e9cd8".into(),
            table: "#7fb4ca".into(),
            column: "#dcd7ba".into(),
            parameter: "#d27e99".into(),
            cte: "#6a9589".into(),
            boolean: "#d27e99".into(),
            null: "#c34043".into(),
            error_underline: "#c34043".into(),
            warning_underline: "#c0a36e".into(),
            info_underline: "#7e9cd8".into(),
            bracket_match: "#76946a".into(),
            bracket_mismatch: "#c34043".into(),
        },
        editor: EditorColors {
            bg: "#1f1f28".into(),
            fg: "#dcd7ba".into(),
            cursor: "#c8c093".into(),
            selection_bg: "#2d4f67".into(),
            line_highlight: "#223249".into(),
            whitespace: "#363646".into(),
            indent_guide: "#363646".into(),
            fold_marker: "#727169".into(),
            minimap_bg: "#16161d".into(),
            minimap_viewport: "#54546d".into(),
        },
        grid: GridColors {
            bg: "#1f1f28".into(),
            header_bg: "#223249".into(),
            header_fg: "#dcd7ba".into(),
            border: "#363646".into(),
            row_even_bg: "#1f1f28".into(),
            row_odd_bg: "#16161d".into(),
            row_selected_bg: "#2d4f67".into(),
            null_fg: "#54546d".into(),
            modified_fg: "#c0a36e".into(),
            cell_focus: "#7e9cd8".into(),
            resize_handle: "#54546d".into(),
        },
    }
}

// ─── Solarized Dark ────────────────────────────────────────────────

pub fn solarized_dark() -> Theme {
    let palette = ColorPalette {
        background: Color::Hex("#002b36".into()),
        foreground: Color::Hex("#839496".into()),
        black: Color::Hex("#073642".into()),
        red: Color::Hex("#dc322f".into()),
        green: Color::Hex("#859900".into()),
        yellow: Color::Hex("#b58900".into()),
        blue: Color::Hex("#268bd2".into()),
        magenta: Color::Hex("#d33682".into()),
        cyan: Color::Hex("#2aa198".into()),
        white: Color::Hex("#eee8d5".into()),
        bright_black: Color::Hex("#002b36".into()),
        bright_red: Color::Hex("#cb4b16".into()),
        bright_green: Color::Hex("#586e75".into()),
        bright_yellow: Color::Hex("#657b83".into()),
        bright_blue: Color::Hex("#839496".into()),
        bright_magenta: Color::Hex("#6c71c4".into()),
        bright_cyan: Color::Hex("#93a1a1".into()),
        bright_white: Color::Hex("#fdf6e3".into()),
        cursor: Color::Hex("#839496".into()),
        selection: Color::Hex("#073642".into()),
    };
    Theme {
        metadata: metadata("solarized-dark", true),
        palette,
        semantic: SemanticColors {
            panel_bg: "#002b36".into(),
            panel_border: "#073642".into(),
            panel_border_active: "#268bd2".into(),
            status_bar_bg: "#073642".into(),
            status_bar_fg: "#839496".into(),
            tab_bar_bg: "#002b36".into(),
            tab_active: "#073642".into(),
            tab_inactive: "#002b36".into(),
            scrollbar_thumb: "#586e75".into(),
            scrollbar_track: "#002b36".into(),
            command_palette_bg: "#073642".into(),
            command_palette_selected: "#586e75".into(),
            error: "#dc322f".into(),
            warning: "#cb4b16".into(),
            info: "#268bd2".into(),
            success: "#859900".into(),
            breadcrumb: "#586e75".into(),
            line_number: "#586e75".into(),
            line_number_active: "#839496".into(),
            gutter_bg: "#002b36".into(),
            search_highlight: "#b58900".into(),
            search_match: "#cb4b16".into(),
        },
        syntax: SyntaxColors {
            keyword: "#d33682".into(),
            datatype: "#b58900".into(),
            string: "#859900".into(),
            number: "#6c71c4".into(),
            comment: "#586e75".into(),
            identifier: "#839496".into(),
            function: "#268bd2".into(),
            operator: "#2aa198".into(),
            punctuation: "#839496".into(),
            alias: "#268bd2".into(),
            table: "#2aa198".into(),
            column: "#839496".into(),
            parameter: "#d33682".into(),
            cte: "#2aa198".into(),
            boolean: "#6c71c4".into(),
            null: "#dc322f".into(),
            error_underline: "#dc322f".into(),
            warning_underline: "#b58900".into(),
            info_underline: "#268bd2".into(),
            bracket_match: "#859900".into(),
            bracket_mismatch: "#dc322f".into(),
        },
        editor: EditorColors {
            bg: "#002b36".into(),
            fg: "#839496".into(),
            cursor: "#839496".into(),
            selection_bg: "#073642".into(),
            line_highlight: "#073642".into(),
            whitespace: "#073642".into(),
            indent_guide: "#073642".into(),
            fold_marker: "#586e75".into(),
            minimap_bg: "#073642".into(),
            minimap_viewport: "#586e75".into(),
        },
        grid: GridColors {
            bg: "#002b36".into(),
            header_bg: "#073642".into(),
            header_fg: "#839496".into(),
            border: "#586e75".into(),
            row_even_bg: "#002b36".into(),
            row_odd_bg: "#073642".into(),
            row_selected_bg: "#586e75".into(),
            null_fg: "#586e75".into(),
            modified_fg: "#b58900".into(),
            cell_focus: "#268bd2".into(),
            resize_handle: "#586e75".into(),
        },
    }
}

// ─── Solarized Light ───────────────────────────────────────────────

pub fn solarized_light() -> Theme {
    let palette = ColorPalette {
        background: Color::Hex("#fdf6e3".into()),
        foreground: Color::Hex("#657b83".into()),
        black: Color::Hex("#eee8d5".into()),
        red: Color::Hex("#dc322f".into()),
        green: Color::Hex("#859900".into()),
        yellow: Color::Hex("#b58900".into()),
        blue: Color::Hex("#268bd2".into()),
        magenta: Color::Hex("#d33682".into()),
        cyan: Color::Hex("#2aa198".into()),
        white: Color::Hex("#93a1a1".into()),
        bright_black: Color::Hex("#fdf6e3".into()),
        bright_red: Color::Hex("#dc322f".into()),
        bright_green: Color::Hex("#859900".into()),
        bright_yellow: Color::Hex("#b58900".into()),
        bright_blue: Color::Hex("#268bd2".into()),
        bright_magenta: Color::Hex("#d33682".into()),
        bright_cyan: Color::Hex("#2aa198".into()),
        bright_white: Color::Hex("#839496".into()),
        cursor: Color::Hex("#586e75".into()),
        selection: Color::Hex("#eee8d5".into()),
    };
    Theme {
        metadata: metadata("solarized-light", false),
        palette,
        semantic: SemanticColors {
            panel_bg: "#fdf6e3".into(),
            panel_border: "#eee8d5".into(),
            panel_border_active: "#268bd2".into(),
            status_bar_bg: "#eee8d5".into(),
            status_bar_fg: "#657b83".into(),
            tab_bar_bg: "#fdf6e3".into(),
            tab_active: "#eee8d5".into(),
            tab_inactive: "#fdf6e3".into(),
            scrollbar_thumb: "#93a1a1".into(),
            scrollbar_track: "#fdf6e3".into(),
            command_palette_bg: "#eee8d5".into(),
            command_palette_selected: "#93a1a1".into(),
            error: "#dc322f".into(),
            warning: "#cb4b16".into(),
            info: "#268bd2".into(),
            success: "#859900".into(),
            breadcrumb: "#93a1a1".into(),
            line_number: "#93a1a1".into(),
            line_number_active: "#657b83".into(),
            gutter_bg: "#fdf6e3".into(),
            search_highlight: "#b58900".into(),
            search_match: "#cb4b16".into(),
        },
        syntax: SyntaxColors {
            keyword: "#d33682".into(),
            datatype: "#b58900".into(),
            string: "#859900".into(),
            number: "#6c71c4".into(),
            comment: "#93a1a1".into(),
            identifier: "#657b83".into(),
            function: "#268bd2".into(),
            operator: "#2aa198".into(),
            punctuation: "#657b83".into(),
            alias: "#268bd2".into(),
            table: "#2aa198".into(),
            column: "#657b83".into(),
            parameter: "#d33682".into(),
            cte: "#2aa198".into(),
            boolean: "#6c71c4".into(),
            null: "#dc322f".into(),
            error_underline: "#dc322f".into(),
            warning_underline: "#b58900".into(),
            info_underline: "#268bd2".into(),
            bracket_match: "#859900".into(),
            bracket_mismatch: "#dc322f".into(),
        },
        editor: EditorColors {
            bg: "#fdf6e3".into(),
            fg: "#657b83".into(),
            cursor: "#586e75".into(),
            selection_bg: "#eee8d5".into(),
            line_highlight: "#eee8d5".into(),
            whitespace: "#eee8d5".into(),
            indent_guide: "#eee8d5".into(),
            fold_marker: "#93a1a1".into(),
            minimap_bg: "#fdf6e3".into(),
            minimap_viewport: "#93a1a1".into(),
        },
        grid: GridColors {
            bg: "#fdf6e3".into(),
            header_bg: "#eee8d5".into(),
            header_fg: "#657b83".into(),
            border: "#93a1a1".into(),
            row_even_bg: "#fdf6e3".into(),
            row_odd_bg: "#eee8d5".into(),
            row_selected_bg: "#93a1a1".into(),
            null_fg: "#93a1a1".into(),
            modified_fg: "#b58900".into(),
            cell_focus: "#268bd2".into(),
            resize_handle: "#93a1a1".into(),
        },
    }
}
